name: Merge upstream branches

on:
  schedule:
    - cron: '0 0 * * 0'
jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git remote add upstream https://github.com/llvm/llvm-project.git
          git fetch upstream

          git checkout main
          git merge --no-edit upstream/main
          git push origin main
