name: Merge upstream branches

on:
  push:
    paths:
      - '.github/workflows/merge-upstream.yml'
  schedule:
    - cron: '0 0 * * 0'
jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.JUICE_LANG_AUTO_MERGER_TOKEN }}
      - run: |
          git config user.name Juice-Lang-Auto-Merger
          git config user.email contact@juicelang.org

          git remote add upstream https://github.com/llvm/llvm-project.git
          git fetch --tags upstream

          git checkout --track origin/main
          git merge --no-edit upstream/main
          git push --tags origin main
